CUDA_VISIBLE_DEVICES=7 python cross/train.py \
    --data_path /data/zfw/NEL/data/partial_nep_vectors/vector_$1p \
    --output_path /data/zfw/NEL/models/partial_nep/cross_blink_$1p \
    --learning_rate 1e-05 \
    --cate_num 187 \
    --num_train_epochs 4 \
    --max_context_length 128 \
    --max_cand_length 128 \
    --train_batch_size 8 \
    --eval_batch_size 32 \
    --cate_ctxt_loss_weight 0 \
    --cate_cand_loss_weight 0 \
    --cate_score_weight 0 \
    --bert_model bert-large-uncased \
    --type_optimization all \
    --training_objective semantic \
    --eval_interval 200000 